
// Objective-C API for talking to the following Go packages
//
//	bulletproofs
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bulletproofs_FRAMEWORK_H__
#define __Bulletproofs_FRAMEWORK_H__

#include "Bulletproofs.objc.h"
#include "Universe.objc.h"

#endif
